# Generated by Django 4.0 on 2022-12-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedetection',
            name='temp_field',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
